### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by Lukemul6** [albertopoljak/Licensy#5]
Adding reactions in the server makes the bot crash. 
users without any roles can generate a license.
Users without any roles can actually use any of the commands.

**Comment by albertopoljak** [comment]
Are we talking about usage of the bot hosted by me or did you self-host the code?

**Comment by Lukemul6** [comment]
Self hosted

**Comment by Lukemul6** [comment]
other than those issues listed above it works perfectly

**Comment by albertopoljak** [comment]
> Adding reactions in the server makes the bot crash.

Since you self-hosted then you need to update d.py to 1.2.5 because Discord made some changes that broke the lib and thus a lot of bots.
The bot hosted by me has the updated lib and doesn't crash on adding reaction.
Also the requirements.txt in this repo specifically target d.py 1.2.5 so you must have somehow messed up your enviroments. You can read more on the issue  [here](https://github.com/Rapptz/discord.py/commit/ade8d03f546c915d8015439da8aa05ffe18a6184)

> users without any roles can generate a license.

> Users without any roles can actually use any of the commands.

The user needs to be administrator, so owner of server even without roles is always considered a administrator. Are you testing this by removing all roles from yourself while being the server owner? Because that would explain it.

**Comment by Lukemul6** [comment]
Yeah I just updated to 1.2.5 and it worked thanks!

I'm using an alt account that has no roles at all in the server. I created a server where the user joins and can only see a redeem channel, after inputting the license they can see the rest of the server. But I joined with the alt typed !generate 5 and 5 keys were sent to DM.

**Comment by albertopoljak** [comment]
Hmm from the [source code you can see](https://github.com/albertopoljak/Licensy/blob/master/cogs/licenses.py#L337) that there's a decorator check and the member who called has to be administrator.

I tried to recreate the problem with my alt just in case but failed, I get error message that I need administrator permissions.

**Comment by Lukemul6** [comment]
Yeah I saw that, I have no idea why its doing that. I just double checked the roles none have admin except the owner and the bot :/

**Comment by albertopoljak** [comment]
That's all I can say for now based on current avaiable information. 
If you want you can join my discord support server (link at the top of this repo readme or you can use https://discordapp.com/invite/trCYUkz ) and invite me there to your server so I can troubleshoot better.

**Comment by albertopoljak** [comment]
Solved so closing.

For future references the issue was that those marked as developers bypass all checks.
Specific code can be found in cogs/cmd_errors.py when dealing with MissingPermissions error.
